### ISSUE TITLE
Cannot create account using ECDSA_secp256k1  key

### ISSUE THREAD

**Issue by philipglazman** [onflow/flow-cli#1230]
### Instructions

```sh
flow accounts create --hash-algo SHA2_256 --sig-algo ECDSA_secp256k1 --key 961d88f85437d89ff8d799d8b9af32985d2fb24d827039bffa6087128c739c6e1f84b88e75f0dc40425bbc40ee053b6c31576577c2947e2f84b20b7ded349fb5 --network mainnet
```

### Problem

I am expecting to create a mainnet account using the provided key and algorithm parameters. However, I am getting the following error:

```sh
❌ Invalid argument: address f8d6e0586b0a20c7 is invalid for chain flow-mainnet 
🙏 Check you are connecting to the correct network or account address you use is correct.
```

### Steps to Reproduce

Run the command from above

**Comment by chasefleming** [comment]
I think it may be defaulting to the `emulator-account` from `flow.json` since no signer is provided. Do you have an existing mainnet account you can use as the signer? See this doc: https://developers.flow.com/tools/flow-cli/accounts/create-accounts#manual-mode

You can use `flow accounts create` to generate another account to act as that role. That error you got is confusing though and should be improved.

**Comment by philipglazman** [comment]
I do not have an existing mainnet account. 

`flow accounts create` works for mainnet, however the newly created account uses the default signature and hash algorithms and ignores flags set in the cli.

**Comment by chasefleming** [comment]
The CLI has two ways of generating accounts: (1) interactive mode and (2) manual mode. When you don't provide any flags, it is interactive mode and will use the default signatures and hash algorithms. In interactive mode, no additional account is needed because the transaction fee to create the account is handled for you, but when you are in manual mode you need an additional account with enough funds to cover the transaction for creating a new account. That's the `--signer my-testnet-account` you see in the example [on this doc](https://developers.flow.com/tools/flow-cli/accounts/create-accounts#manual-mode). I can see how the command being the same in both cases may be confusing and maybe we might want to think about changing them to differentiate between interactive and manual more. Also, if you're not on the Flow Discord, there are a lot of helpful community members that give pretty quick responses to questions like this. I'm on there too!

**Comment by philipglazman** [comment]
Thanks @chasefleming! That explains my confusion. Noted, on Discord - just joined.

**Comment by chasefleming** [comment]
Awesome @philipglazman , see you on there!
