### ISSUE TITLE
emulator pkey

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/flow-cli#1325]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

When you run `flow init`, it puts the emulator pkey inside the flow.json file. When you then take any action on testnet/mainnet using Flow CLI, it complains about the emulator pkey being in the flow.json file.

### Suggested Fix

When a user runs `flow init`, make a `emulator-account.pkey` file that holds the emulator private key so it no longer complains. Very similar to how `testnet-account.pkey` gets made when you run `flow accounts create`

**Comment by chasefleming** [comment]
Agreed I've wanted this for awhile as well, it's probably best we should probably show the suggested pattern from the first example a user encounters, even though it's just emulator as to not teach bad habits. This separate key location pattern is also the default with `flow accounts create` so it should be consistent and familiar enough. Thanks for adding this issue @jacob-tucker .

**Comment by ianthpun** [comment]
im kind of inclined to keeping the emulator pkey in the `.gitignore`. simply because it would fire off some security checks like synk, even if the private key is the same. It also sets a better precidence that there shouldn't be an exceptions of `.pkey` being able to be commmitted. @jacob-tucker  thoughts?
