### ISSUE TITLE
Facilitate Switch to Dependency Manager on Existing Projects

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#1544]
In order to more easily migrate people with existing projects to use Dependency Manager, we should facilitate the switch easily. This means:

- And existing project adds a dependency
- If it detects that dependency in contracts it asks the user if they'd like to remove it from contracts since it will be in dependencies
- It pulls the aliases (may request permission)
- It gives a summary of files you can now delete from your project

**Comment by btspoony** [comment]
There are still some incompatibilities with the dependency manager in VS Code.
I have to configure the same contract twice in contracts and dependencies to ensure that `flow.json` works properly.

Of course, the advantage is that I don't have to submit these contracts to the repo anymore, because they are under `imports` folder.

For your refer: 
https://github.com/onflow/vscode-cadence/issues/542

**Comment by chasefleming** [comment]
Looks like this was fixed on the other ticket. Going to close.

**Comment by chasefleming** [comment]
I'm not sure this is related to this ticket, but it looks like it was resolved on the linked issue.

**Comment by btspoony** [comment]
Yeah, I found that it has been fixed in flow-cli v1.18.0 .
