### ISSUE TITLE
"flow accounts create", flags is not working

### ISSUE THREAD

**Issue by daorren** [onflow/flow-cli#1658]
### Problem
I specify sig-algo & network, but it turned out to be a sig-algo=ECDSA_P256 key

<img width="1240" alt="2024-06-20_15 50 30" src="https://github.com/onflow/flow-cli/assets/8929965/b2bf7eba-4e97-4008-97aa-41cd877ee17a">

### Context

flow-cli version: v1.20.5

**Comment by chasefleming** [comment]
I looked into the code and it looks like it actually wants the key and weight in order to skip interactive mode (which is the mode where you are picking the network instead of giving the flag). The logic has some issues, so thank you for reporting it, but you should be able to get around this in the meantime by also providing a key and weight.

**Comment by daorren** [comment]
OK I got it, I can create my first key with default config, then use it to generate a new one with custom config

**Comment by chasefleming** [comment]
Check this out too: https://developers.flow.com/tools/flow-cli/keys/generate-keys
