### ISSUE TITLE
Refactor command structure?

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#29]
This is more of an idea than anything else, but I'd like to take second look at our command structure and make sure it's the right pattern for us to commit to going forward.

In particular, I'm wondering if it makes sense to flatten the command structure:

```
flow accounts get
```

to something like this:

```
flow get-account
```

Currently our commands are grouped by entity (e.g. transaction, block, collection) but I'm not sure how well that scales. 

For example, which of the two options below is clearer?

```
flow accounts get
flow blocks get
flow transactions get
flow collections get
```
```
flow get-account
flow get-block
flow get-transaction
flow get-collection
```

**Comment by sideninja** [comment]
Currently, there are the following commands:

```
accounts
- add-contract
- create
- get 
- update-contract

blocks
- get

cadence (first-class command)

collections
- get

emulator
- start

help (first-class command)

init (first-class command)

keys
- generate
- save

project
- deploy-contracts
- init
- start-emulator

scripts
- execute

transactions
- send
- status

version (first-class command)
```

Flatten command list could potentially look like:
```
deploy-contract
update-contract
create-account
get-account
get-block
get-collection
start-emulator
help
cadence
init
generate-keys
execute-script
send-transaction
transaction-status
```

There are 11 commands in total in the current structure only 4 of which have more than 1 subcommand. I believe having a single subcommand is not that useful. 
Naming should be different for each case. In current/first case you have a naming based on resources `accounts`, `blocks` etc in the second case naming is based on actions `get-account`, `get-block`. This should be defined further as part of guidelines #59 

In my opinion, the most important thing is consistency. Commands should follow a pattern so users can expect the behavior. 

Pros of flattening command structure:
- potentially less commands 
- it is easier to discover commands

The flat structure will probably need more command options.

Currently flat structure looks easier to use, but it opens questions like: 
- deploy-contracts (should this command be separate from the previous `project deploy`)
- there might be some confusion on which command since there is an overlap with project commands

**Comment by psiemens** [comment]
Moving to next sprint!
