### ISSUE TITLE
Start emulator without validation

### ISSUE THREAD

**Issue by 10thfloor** [onflow/flow-cli#327]
### Problem:

Given a `flow.json` with the following accounts: 
```
 "accounts": {
    "emulator-account": {
      "address": "f8d6e0586b0a20c7",
      "keys": "f8e188e8af0b8b414be59c4a1a15cc666c898fb34d94156e9b51e18bfde754a5"
    },
    "testnet-account": {
      "address": "${FLOW_ADDRESS}",
      "keys": "${FLOW_PRIVATE_KEY}"
    }
  },
```

It is not possible to start the emulator without the values for testnet (`FLOW_ADDRESS` / `FLOW_PRIVATE_KEY`) existing in the runtime environment.

### Use Case:

For Kitty Items, I would like to use the existing Kitty Items `flow.json` to create automated tests that run against the emulator _only_, in CI. 

- I don't want to also export the testnet values for the testnet account into the shell so that I can start the emulator.
- I don't want to create another 'emulator only' `flow.json` file. (ie I don't want to have to remove the testnet account configs when they aren't being used in my workflow).

### Potential Solutions:

1) When the emulator is started use a flag like `---only=emulator` that tells the cli: _don't_ run validation on _any_ testnet configs.

2) Implement a flag to bypass validation:
```
flow emulator start --novalidate
```

**Comment by sideninja** [comment]
I think that it would be better to use other features of the CLI configuration to achieve this task. 
I don't think it would be a good idea to ignore validation in my opinion this is not a good precedent for testing (as some other things can go wrong in the config) and also not a great example. 
I've written the security documentation https://docs.onflow.org/flow-cli/security/ where there are other options on how you can use configuration. I think it could be useful to have a separate file for testnet configuration and then use composition. In the case where you don't need that private config, you don't include it. I believe that approach can also more secure as it doesn't expose private keys to the env.

**Comment by 10thfloor** [comment]
I just want to be able to start the emulator without exporting the variables for the testnet config.
Right now, I can't start the emulator to work locally if those vars aren't exported (for testnet)

it should not try to validate the testnet configs when running the emulator, It should only validate the testnet configs when you attempt to deploy to testnet no?

**Comment by sideninja** [comment]
The configuration gets loaded as part of the state loading and it is separated from the context of running the command, meaning the configuration loading process has no awareness of which command is being executed, that is because of the architectural separation of concerns. The state is something that should be correct no matter which part you are using the same way a Go program must be free of syntax errors even if you are not executing that part. 

There are other solutions offered to achieve tasks like yours which is either config composition where you can list multiple configurations you want to use and they get merged like: `flow emulator -f testnet.json` (using default flow json merged with testnet config) or `flow emulator` (using just default flow.json), or by making a `.env` file containing testnet variables pointing to some dummy values just to pass the validation of the testing.

**Comment by bjartek** [comment]
flow-cli uses envsubst, and it supports default values. so try with 
```
${FLOW_ADDRESS:=f8d6e0586b0a20c7}
${FLOW_PRIVATE_KEY:=f8e188e8af0b8b414be59c4a1a15cc666c898fb34d94156e9b51e18bfde754a5}
```

or something like that?
