### ISSUE TITLE
Create tests for internal/cmd

### ISSUE THREAD

**Issue by sukantoraymond** [onflow/flow-cli#527]
Create tests for commands in internal/cmd

I am thinking we can create test files under internal for each command. So for example to test accounts get, we will create get_test.go under internal/accounts. 

In the example of accounts get, We can run the following test 

````
package accounts

import (
	"bytes"
	"fmt"
	"github.com/stretchr/testify/assert"
	"strings"
	"testing"
)

func TestAccountsGetCmd(t *testing.T) {
        cmdOutput := new(bytes.Buffer)
	Cmd.SetOut(cmdOutput)
	Cmd.SetErr(cmdOutput)
	Cmd.SetArgs([]string{"get", "0xf8d6e0586b0a20c7"})
	Cmd.Execute()
        expected := "This-is-command-a1"
        assert.Equal(t, actual.String(), expected, "actual is not expected")
}
````

To run this test however, we need emulator running and I am thinking we can use the emulator start function called from flow emulator
````
Cmd = start.Cmd(ConfiguredServiceKey)
Cmd.Use = "emulator"
````

Not sure how we can have emulator running in parallel while we are running the tests for cli commands though

**Comment by sideninja** [comment]
You could use the hosted emulator version instead of an actual separate service. Take a look at this test to see how to do it: https://github.com/onflow/flow-cli/blob/53f12e7508b768a2789a521a6db345e6b546b2ce/pkg/flowkit/services/accounts_test.go#L50

I think the above approach is good, the only problem and the hard part you would need to think about before is how will you assert the output? The problem becomes that the output might be very sensitive to indentations, spacing etc. It might be a good idea to try to process the output with a function that is a bit more abstract than exact character by character match.

**Comment by sideninja** [comment]
Closed in favour of https://github.com/onflow/flow-cli/issues/330
