### ISSUE TITLE
Block Status

### ISSUE THREAD

**Issue by Kay-Zee** [onflow/flow-cli#576]
### Issue To Be Solved

Currently, when calling `flow blocks get`, we see the block, but nothing about it's status (i.e. finalized, executed, or sealed). It would be nice to see the status of the block

### (Optional): Suggest A Solution

We will likely have to implement something on the Access API side as well, unless we want to do multiple calls for this one command.

**Comment by simonhf** [comment]
Following :-)

**Comment by simonhf** [comment]
FYI I have been using a wrapper around `flow-cli` to calculate the output TPS of e.g. localnet. This seems to work okay at lower input TPS levels (e.g. < 260 TPS) because the finalized and executed block states are similar. But with higher input TPS then currently `flow-cli` effectively 'only' shows the block finalization rate which can be much faster than the block executed rate. For example, at input TPS 600 on localnet then `flow-cli` can currently be used to report a block finalization average output TPS of ~ 600 TPS, but in reality the block executed average output TPS is only ~ 260 TPS (known by inspecting the node logs). I would love to see this feature implemented to have another and more efficient way to gauge the block executed average output TPS without necessarily having to go to the trouble of examining the node logs :-)

**Comment by Kay-Zee** [comment]
Also, an addition here, is being able to specify if you want Sealed blocks only

**Comment by bluesign** [comment]
@chasefleming you can take this if you want, I have something else on my plate already. ( sorry I didn't see you assigned this to yourself already )
