### ISSUE TITLE
CLI design guidelines

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-cli#59]
### Issue To Be Solved

We should update the [CONTRIBUTING.md](https://github.com/onflow/flow-cli/blob/master/CONTRIBUTING.md) document to include design guidelines for the CLI. 

This should includes things like:
- Command structure
- Arguments and flag format
- Documentation standards

**Comment by bjartek** [comment]
Also it would be nice if the code was strucutured so that it would be possible to use the actions behind a cli command from a library. This basically means not putting lot of code inside the cmd layer but putting it just a single step behind there and leave all interaction between the user and the code in the cmd layer.

**Comment by sideninja** [comment]
Opened a PR for this #83 still work in progress tho.

**Comment by psiemens** [comment]
> Also it would be nice if the code was structured so that it would be possible to use the actions behind a cli command from a library. This basically means not putting lot of code inside the cmd layer but putting it just a single step behind there and leave all interaction between the user and the code in the cmd layer.

@bjartek Check out this issue! https://github.com/onflow/flow-cli/issues/80

**Comment by bjartek** [comment]
Yes!

**Comment by sideninja** [comment]
Implemented in #100
