### ISSUE TITLE
fcl-dev-wallet folder structure changes break flow-cli build

### ISSUE THREAD

**Issue by gpavlov2016** [onflow/flow-cli#620]
In the current master of the [fcl-dev-wallet](https://github.com/onflow/fcl-dev-wallet), the go files were moved into internal folder go/wallet but the import in [wallet.go](https://github.com/onflow/flow-cli/blob/master/internal/tools/wallet.go) was not updated which leads to an error during build.
The breaking update to fcl-dev-wallet was not released yet so build doesn't fail while using the latest official version 0.39 . When new version is created off of master it will break flow-cli builds

**Comment by sideninja** [comment]
The CLI won't break if a version of dev-wallet is released since it doesn't include that version, after we update the version in the CLI to include the latest version of dev-wallet we will need to update the changes made in dev-wallet as you mentioned. This is part of the normal process. I also believe dev-wallet should be built as it is, at least it did when I made those changes.  Also currently the master of the CLI builds fine. Should we close this or I don't understand something?
