### ISSUE TITLE
About homebrew flow

### ISSUE THREAD

**Issue by chenrui333** [onflow/flow-cli#725]
👋 Just saw that there is [some pre-release version bump PR](https://github.com/Homebrew/homebrew-core/pull/116891), maybe update the homebrew flow to be only triggered on the latest stable release? Thanks!

**Comment by sideninja** [comment]
Hey @chenrui333 sorry for the late reply. We can change it to release only but we made it as part of the pre-release intentionally. At the same time, I would like to know how you otherwise suggest handling the distribution of pre-releases through brew? I was looking at the docs and I don't find any mention of pre-release or beta distribution. The way I see it is we should use brew to distribute our public beta (which we mark as pre-release) but brew shouldn't on running `brew upgrade` to update to that version as it's not latest. Is that supported? Am I misunderstanding brew usage?
