### ISSUE TITLE
Flow super-commands feedback

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-cli#773]
### Issue To Be Solved

- [ ] Nit: some links to more resources are missing in README (“here” should probably be a link to a resource)
<img width="910" alt="Screenshot 2023-01-15 at 19 44 50" src="https://user-images.githubusercontent.com/36109955/212636598-e4c44c52-ec3d-4f25-a8d6-46b95a6d2920.png">

- [ ] Nit: rename origin remote to something else (git remote rename origin flow) or just reinitialize git repo to get rid of scaffold repo commits
<img width="1285" alt="Screenshot 2023-01-15 at 19 45 35" src="https://user-images.githubusercontent.com/36109955/212636649-f76b779c-0564-4f22-92c8-1ef0076e6351.png">

- [ ] `flow dev` is adding a single contract to multiple accounts?
<img width="886" alt="Screenshot 2023-01-15 at 16 17 33" src="https://user-images.githubusercontent.com/36109955/212636734-6150f2d3-f002-4020-a52e-43737d8aa054.png">

- [ ] How does flow dev name accounts? It’d be good to reuse that naming convention in other tools (e.g. Flowser, VS Code extension,…) too

**Comment by sideninja** [comment]
Thank you for your feedback. 
The instructions need polishing for sure. I'm making a PR as we speak https://github.com/onflow/flow-cli/pull/774

The removal of origin is referenced here https://github.com/onflow/flow-cli/issues/749  but thank you for sharing.

Adding of the secrets contract is really weird. Are you sure this is added by `flow dev` command? I'm not sure where this contract would come from, the commands are not adding it explicitly. Interesting. 

Flow dev just creates the accounts you explicitly want to be created by adding a folder inside the contracts folder (as mentioned in the PR docs). There shouldn't be any additional accounts created. But I agree, aligning is good. I don't see a conflict here. Flowser can create the accounts it needs and add them to flow.json, or even better, I believe would be to just have them in-memory so they don't "pollute" flow.json, since they will probably just be used to test and interact.

**Comment by bjartek** [comment]
so when using overflow the integration tests have to be in the same folder as flow.json because flowkit does not support relative paths for loading. So if my test is in /tests and i load flow.json from ../ it has to resolve anything from that /tests folder and that does not work for other things. Is it possible to fix flowkit so that it can specify relative paths for where it expects flow.json to be?

**Comment by sideninja** [comment]
> so when using overflow the integration tests have to be in the same folder as flow.json because flowkit does not support relative paths for loading. So if my test is in /tests and i load flow.json from ../ it has to resolve anything from that /tests folder and that does not work for other things. Is it possible to fix flowkit so that it can specify relative paths for where it expects flow.json to be?

Yes. Can you open a separate issue. I was looking into that the last time. The only thing is that it gets a bit more complex when you compose multiple configurations. But in any case for sure something that should be fixed.
