### ISSUE TITLE
Improve scaffold instructions

### ISSUE THREAD

**Issue by chasefleming** [onflow/flow-cli#973]
The scaffold instructions are generic. Wondering if there is a way to make them specific to the scaffold so that it's clearer. e.g. "npm install" and "npm run dev" for the web dapp scaffold.

![Screenshot 2023-04-13 at 9 46 44 AM](https://user-images.githubusercontent.com/1666730/231828854-f8208ec6-1287-4793-9446-b26c4abfcab1.png)

**Comment by sideninja** [comment]
I like the idea. In this state, a developer is supposed to check the readme of the scaffold where they can find further instructions. We could possibly include that content on the screen after creating the scaffold, but it might be too much content to display. We could say that each scaffold is required to have short step-by-step instructions which we can display instead of the current one, but I'm concerned about whether such short step-by-step instructions are even possible for some scaffolds.

**Comment by chasefleming** [comment]
Yeah if it exists in say a specific file of a repo we could show it otherwise default back to this

**Comment by nialexsan** [comment]
https://github.com/onflow/flow-cli/issues/1795
